name: image

on:
  push:
    branches: [ argocd ]
  pull_request:
    branches: [ argocd ]

jobs:
  pull-image:
    runs-on: ubuntu-latest
    steps:
      - name: pull & push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          docker pull quay.io/argoproj/argocd-applicationset:v0.4.1
          docker tag quay.io/argoproj/argocd-applicationset:v0.4.1 xzxwl/argocd-applicationset:v0.4.1
          docker push xzxwl/argocd-applicationset:v0.4.1
          
