name: image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pull-image:
    runs-on: ubuntu-latest
    steps:
      - name: pull & push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          docker pull quay.io/cilium/cilium:v1.12.3
          docker tag quay.io/cilium/cilium:v1.12.3 xzxwl/cilium:v1.12.3
          docker push xzxwl/cilium:v1.12.3
          
          docker pull quay.io/cilium/certgen:v0.1.8@sha256:4a456552a5f192992a6edcec2febb1c54870d665173a33dc7d876129b199ddbd
          docker tag quay.io/cilium/certgen:v0.1.8@sha256:4a456552a5f192992a6edcec2febb1c54870d665173a33dc7d876129b199ddbd xzxwl/certgen:v0.1.8@sha256:4a456552a5f192992a6edcec2febb1c54870d665173a33dc7d876129b199ddbd
          docker push xzxwl/certgen:v0.1.8@sha256:4a456552a5f192992a6edcec2febb1c54870d665173a33dc7d876129b199ddbd
          
          
