name: image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pull-image:
    runs-on: ubuntu-latest
    steps:
      - name: pull & push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker pull k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0 
          docker tag k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0 xzxwl/csi-node-driver-registrar:v2.5.0
          docker push xzxwl/csi-node-driver-registrar:v2.5.0
          
          docker pull k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
          docker tag k8s.gcr.io/sig-storage/csi-resizer:v1.4.0 xzxwl/csi-resizer:v1.4.0
          docker push xzxwl/csi-resizer:v1.4.0
          
          docker pull k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
          docker tag k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0 xzxwl/csi-provisioner:v3.1.0
          docker push xzxwl/csi-provisioner:v3.1.0
          
          docker pull k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
          docker tag k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1 xzxwl/csi-snapshotter:v5.0.1
          docker push xzxwl/csi-snapshotter:v5.0.1
          
          docker pull k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
          docker tag k8s.gcr.io/sig-storage/csi-attacher:v3.4.0 xzxwl/csi-attacher:v3.4.0
          docker push xzxwl/csi-attacher:v3.4.0
          
          docker pull k8s.gcr.io/sig-storage/nfsplugin:v3.1.0
          docker tag k8s.gcr.io/sig-storage/nfsplugin:v3.1.0 xzxwl/nfsplugin:v3.1.0
          docker push xzxwl/nfsplugin:v3.1.0
