name: image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pull-image:
    runs-on: ubuntu-latest
    steps:
      - name: pull & push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker pull k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
          docker tag k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1 xzxwl/csi-node-driver-registrar:v2.0.1
          docker push xzxwl/csi-node-driver-registrar:v2.0.1
          docker pull k8s.gcr.io/sig-storage/csi-attacher:v3.0.2
          docker tag k8s.gcr.io/sig-storage/csi-attacher:v3.0.2 xzxwl/csi-attacher:v3.0.2
          docker push xzxwl/csi-attacher:v3.0.2
          
          docker pull k8s.gcr.io/sig-storage/csi-provisioner:v2.0.4
          docker tag k8s.gcr.io/sig-storage/csi-provisioner:v2.0.4 xzxwl/csi-provisioner:v2.0.4
          docker push xzxwl/csi-provisioner:v2.0.4
          
          docker pull k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.2
          docker tag k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.2 xzxwl/csi-snapshotter:v3.0.2
          docker push xzxwl/csi-snapshotter:v3.0.2
          
